# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/eliezer/software/clion-2016.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/eliezer/software/clion-2016.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eliezer/Dropbox/repo-phd/poissoncpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eliezer/Dropbox/repo-phd/poissoncpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/eliezer/software/clion-2016.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/eliezer/software/clion-2016.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eliezer/Dropbox/repo-phd/poissoncpp/CMakeFiles /home/eliezer/Dropbox/repo-phd/poissoncpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eliezer/Dropbox/repo-phd/poissoncpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named poisson_scr_cpp

# Build rule for target.
poisson_scr_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poisson_scr_cpp
.PHONY : poisson_scr_cpp

# fast build rule for target.
poisson_scr_cpp/fast:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/build
.PHONY : poisson_scr_cpp/fast

BatchPoissonPure.o: BatchPoissonPure.cpp.o

.PHONY : BatchPoissonPure.o

# target to build an object file
BatchPoissonPure.cpp.o:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/BatchPoissonPure.cpp.o
.PHONY : BatchPoissonPure.cpp.o

BatchPoissonPure.i: BatchPoissonPure.cpp.i

.PHONY : BatchPoissonPure.i

# target to preprocess a source file
BatchPoissonPure.cpp.i:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/BatchPoissonPure.cpp.i
.PHONY : BatchPoissonPure.cpp.i

BatchPoissonPure.s: BatchPoissonPure.cpp.s

.PHONY : BatchPoissonPure.s

# target to generate assembly for a file
BatchPoissonPure.cpp.s:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/BatchPoissonPure.cpp.s
.PHONY : BatchPoissonPure.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/poisson_scr_cpp.dir/build.make CMakeFiles/poisson_scr_cpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... poisson_scr_cpp"
	@echo "... BatchPoissonPure.o"
	@echo "... BatchPoissonPure.i"
	@echo "... BatchPoissonPure.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

